-- ==========================================================
-- SPORTS TURF PROFIT OPTIMIZER
-- PostgreSQL Database Schema
-- ==========================================================

-- Drop tables if they already exist (in reverse dependency order)
DROP TABLE IF EXISTS campaigns CASCADE;
DROP TABLE IF EXISTS recommendations CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS slots CASCADE;
DROP TABLE IF EXISTS arenas CASCADE;

-- ----------------------------------------------------------
-- 1. arenas
-- ----------------------------------------------------------
CREATE TABLE arenas (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------
-- 2. slots
-- ----------------------------------------------------------
CREATE TABLE slots (
    id SERIAL PRIMARY KEY,
    arena_id INTEGER NOT NULL REFERENCES arenas(id) ON DELETE CASCADE,
    sport VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
    normal_price NUMERIC(10, 2) NOT NULL CHECK (normal_price >= 0),
    period VARCHAR(20) NOT NULL CHECK (period IN ('PEAK', 'NON_PEAK')),
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'BOOKED', 'BLOCKED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------
-- 3. customers
-- ----------------------------------------------------------
CREATE TABLE customers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------
-- 4. bookings
-- ----------------------------------------------------------
CREATE TABLE bookings (
    id SERIAL PRIMARY KEY,
    slot_id INTEGER NOT NULL REFERENCES slots(id) ON DELETE CASCADE,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    booking_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    original_price NUMERIC(10, 2) NOT NULL CHECK (original_price >= 0),
    discount_percentage NUMERIC(5, 2) DEFAULT 0.00 CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
    discount_amount NUMERIC(10, 2) DEFAULT 0.00 CHECK (discount_amount >= 0),
    final_price NUMERIC(10, 2) NOT NULL CHECK (final_price >= 0),
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED', 'CANCELLED', 'COMPLETED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------
-- 5. recommendations
-- Stores decisions generated by the profit optimization agent
-- ----------------------------------------------------------
CREATE TABLE recommendations (
    id SERIAL PRIMARY KEY,
    slot_id INTEGER NOT NULL REFERENCES slots(id) ON DELETE CASCADE,
    recommended_action VARCHAR(50) NOT NULL CHECK (recommended_action IN (
        'DO_NOTHING',
        'NOTIFY',
        'LOYALTY_REWARD',
        'EXTENSION',
        'DISCOUNT',
        'NOTIFY_AND_DISCOUNT'
    )),
    reason TEXT,
    booking_probability NUMERIC(5, 4) CHECK (booking_probability >= 0.0000 AND booking_probability <= 1.0000),
    expected_revenue NUMERIC(10, 2) CHECK (expected_revenue >= 0),
    expected_profit NUMERIC(10, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------
-- 6. campaigns
-- Stores customer outreach and targeted marketing campaigns
-- ----------------------------------------------------------
CREATE TABLE campaigns (
    id SERIAL PRIMARY KEY,
    slot_id INTEGER NOT NULL REFERENCES slots(id) ON DELETE CASCADE,
    campaign_type VARCHAR(50) NOT NULL CHECK (campaign_type IN (
        'NOTIFICATION',
        'LOYALTY_REWARD',
        'DISCOUNT',
        'NOTIFY_AND_DISCOUNT'
    )),
    target_customer_count INTEGER DEFAULT 0 CHECK (target_customer_count >= 0),
    message TEXT,
    discount_percentage NUMERIC(5, 2) DEFAULT 0.00 CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN (
        'DRAFT',
        'SENT',
        'COMPLETED',
        'CANCELLED'
    )),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- INDEXES FOR QUERY OPTIMIZATION
-- ==========================================================

-- Fast queries for vacant and non-peak slots
CREATE INDEX idx_slots_vacant ON slots(status) WHERE status = 'AVAILABLE';
CREATE INDEX idx_slots_period ON slots(period);
CREATE INDEX idx_slots_date_arena ON slots(arena_id, date);
CREATE INDEX idx_slots_sport_date_time ON slots(sport, date, start_time);
CREATE INDEX idx_slots_period_status ON slots(period, status);

-- Bookings lookups
CREATE INDEX idx_bookings_slot_id ON bookings(slot_id);
CREATE INDEX idx_bookings_customer_id ON bookings(customer_id);
CREATE INDEX idx_bookings_status ON bookings(status);
CREATE INDEX idx_bookings_booking_time ON bookings(booking_time);

-- Recommendations and campaigns lookups
CREATE INDEX idx_recommendations_slot_id ON recommendations(slot_id);
CREATE INDEX idx_campaigns_slot_id ON campaigns(slot_id);
CREATE INDEX idx_campaigns_status ON campaigns(status);
